version: '3.4'

services:
    node:
        container_name: node_server
        build: .
        ports:
            - 5000:5000
        volumes:
            - .:/app

        networks:
            - common
        restart: always
        environment:
            PORT: 5000
            CLIENT_URL: 'http://localhost:3000'
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
        networks:
            - common

networks:
    common:
